org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Trouble telling your potions apart? Time to give you a helping hand with that.
mod.group=fuzs.distinctpotions
mod.id=distinctpotions
mod.license=MPL-2.0
mod.name=Distinct Potions
mod.version=26.2.0

dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=682565
distributions.curseforge.slug=distinguished-potions
distributions.github.slug=distinct-potions
distributions.modrinth.id=lX1xTFBZ
distributions.modrinth.slug=distinguished-potions

environments.client=required
environments.server=unsupported
